version: '3'

services:
  my_nginx:
    container_name: my_nginx
    image: nginx
    ports:
      - "81:80"
    volumes:
      - ./api/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./api/nginx/www:/var/www/public_html
    depends_on:
      - api
      - db
  api:
    container_name: api
    build: ./api/php
    volumes:
      - ./api/nginx/www:/var/www/public_html
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: calorize_db
    volumes:
      - mysql_data:/var/lib/mysql
  web:
    container_name: web
    build: ./web
    ports:
      - "5000:3000"
  adminer:
    image: adminer
    restart: always
    ports:
      - '8888:8080'
    depends_on:
      - db

volumes:
  mysql_data:

